services:
  - type: web
    name: cbc-contratos-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
